services:
  - type: web
    name: nifty-backend
    env: docker
    plan: starter   # change to free if you want free tier
    dockerfilePath: ./niftypred/Dockerfile
    dockerContext: ./niftypred
    envVars:
      - key: FLASK_ENV
        value: development
      - key: FLASK_DEBUG
        value: "1"
    healthCheckPath: /api/health
    disk:
      name: nifty-data
      mountPath: /app/data
      sizeGB: 10

  - type: web
    name: nifty-frontend
    env: docker
    plan: starter
    dockerfilePath: ./nifty-prediction-app/Dockerfile
    dockerContext: ./nifty-prediction-app
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: nifty-backend
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /health
    disk:
      name: nifty-models
      mountPath: /app/saved_model
      sizeGB: 5
